/* 🧱 DDL (Data Definition Language)

Create a table named Restaurants with appropriate columns from the Swiggy dataset.

Alter the Restaurants table to add a column Average_Rating.

Modify the datatype of Restaurant_Name column to VARCHAR(100).

Rename the column Cost_for_Two to Avg_Cost_for_Two.

Drop the column Cuisine_Type from the Restaurants table.

Create a new table Orders with columns for order details.

Add a foreign key constraint between Orders and Restaurants.

Create a unique constraint on Restaurant_Name.

Rename table Restaurants to Swiggy_Restaurants.

Drop the Swiggy_Restaurants table.

✍️ DML (Data Manipulation Language)

Insert a new restaurant record into the Restaurants table.

Update the Average_Rating for all restaurants with more than 500 orders.

Delete all restaurants having null values in the City column.

Retrieve all restaurant names and cities from the table.

Show all restaurants where Cost_for_Two is greater than 1000.

Display the top 5 restaurants with the highest ratings.

Find all restaurants that serve North Indian cuisine.

Count how many restaurants are available in each city.

Show the average cost for two per city.

Display all restaurants sorted by rating in descending order.

🔗 JOINS

(Assume you have related tables like Restaurants, Orders, Customers.)

Display restaurant names along with the number of orders each received.

Show customer names with their ordered restaurant names.

List all restaurants and their corresponding customer details (use INNER JOIN).

Show all restaurants even if they have no orders (use LEFT JOIN).

Show all customers even if they haven’t placed any order (use RIGHT JOIN).

Show all restaurants and customers (whether orders exist or not) — use FULL OUTER JOIN.

Display all orders with both restaurant name and customer name.

Show total order amount per restaurant using a JOIN.

Find restaurants where the same customer placed more than one order.

Show top 3 customers by number of orders and their favorite restaurant.

⚙️ STORED PROCEDURES

Create a stored procedure to insert new restaurant data.

Create a stored procedure to update restaurant rating based on new reviews.

Create a stored procedure to delete a restaurant by ID.

Write a stored procedure to fetch all restaurants with cost above a given value.

Create a procedure to show all restaurants in a specific city (parameterized).

Write a stored procedure to calculate the total revenue of all orders for a given restaurant.

Create a procedure that returns the top 5 highest-rated restaurants.

Create a stored procedure to insert a new order with restaurant and customer details.

Create a procedure to show average rating and total orders for each cuisine type.

Create a stored procedure to display all restaurants created within a specific date range.

🧮 FUNCTIONS

Create a function to return average cost for two across all restaurants.

Write a function to calculate discount based on order amount.

Create a function that returns total number of restaurants in a city.

Write a scalar function to return restaurant rating category (‘High’, ‘Medium’, ‘Low’).

Create a function to fetch total orders for a given restaurant ID.

Write a function that returns restaurant names having rating above 4.5.

Create a table-valued function to list all restaurants serving a given cuisine.

Write a function to calculate delivery time category based on minutes.

Create a function to return most ordered cuisine type.

Create a function to return total revenue generated by a given restaurant.

🚨 TRIGGERS

Create a trigger to log every time a new restaurant is inserted.

Create a trigger to prevent deletion of a restaurant if it has active orders.

Create a trigger that updates Last_Updated_Date when restaurant data is updated.

Write a trigger to record all deleted restaurant records in a Deleted_Restaurants_Log table.

Create a trigger to automatically calculate and update average rating after an order review is inserted.

Create a trigger to stop inserting records if Cost_for_Two is less than 50.

Create a trigger to maintain audit history for updates in the Orders table.

Create a trigger to send notification (log entry) when a restaurant’s rating drops below 3.

Write a trigger that updates restaurant’s total orders count whenever a new order is inserted.

Create a trigger to rollback transaction if restaurant name already exists (prevent duplicates).*/